services:
  crimson_bot:
    build: .
    restart: always
    container_name: CrimsonBot
    environment:
      - DATA=/bot/data # The bots data directory inside the container
      - CONFIG=./config.yml # The bots config file relative to the DATA directory
    volumes:
      - .:/bot
